---
- name: Setup CE3S Stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:

    - name: Import VPC setup Variable
      include_vars: vars/vpc-output_vars

    - name: Import CE3S setup Variable
      include_vars: vars/ec2StackSetup

    - name: Create CE3S ec2 key
      ec2_key:
        name: CE3Skey
        region: "{{ region }}"
      register: CE3Skey_out

    - name: Save private key into file loginkey_ce3s.pem
      copy:
        content: "{{ CE3Skey_out.key.private_key }}"
        dest: "./loginkey_ce3s.pem"
        mode: 0600
      when: CE3Skey_out.changed

    - name: Create Security Group for Load Balancer
      ec2_group:
        name: CE3SELB-sg
        description: Allow port 80 from everywhere and all port within sg
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: CE3SELBSG_out

    - name: Create Security Group for CE3S Stack
      ec2_group:
        name: CE3SStack-sg
        description: Allow port 22 from everywhere and all port within sg
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{ CE3SStack-sg_out.group_id }}"

          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{ BastionSGid }}"
      register: CE3SStack-sg_out

    - name: Update Security Group with its own sg id
      ec2_group:
        name: CE3SStack-sg
        description: Allow port 22 from everywhere and all port within sg
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        purge_rules: no
        rules:
          - proto: all
            group_id: "{{ CE3SStack-sg_out.group_id }}"
